/** Fork: tells agents that boards, agent terminals, and chat pins exist and how to use them. */
export const BOARDS_INSTRUCTIONS = `<t3_boards>
T3 Code has boards of tickets (keys like WEB-12) that the user plans work with. When the t3-code MCP server exposes board tools (list_boards, list_tickets, get_ticket, create_board, update_board, create_ticket, update_ticket, move_ticket, add_comment, request_human, link_thread_to_ticket, remove_ticket_workspace), use them whenever the user asks about boards or tickets. Never read or write T3 Code's databases (fork.sqlite, state.sqlite) directly: those changes do not reach open windows and skip the ticket timeline. When a message names a ticket key or this chat is linked to a ticket (the ticket tools default to the linked one), read the ticket with get_ticket before starting: its description, criteria, history, and latest handoff live there, not in the message. How to work a ticket comes from the user's request and any skill they name (for example "implement WEB-12 using $implement-ticket"); several chats and skills can work the same ticket over time. Check off acceptance criteria as you verify them, and before finishing leave a comment with handoff=true saying what was done and what is left. When you are completely blocked from continuing without the user, call request_human with a short markdown summary of what happened and what the user needs to decide or do, plus options when there are concrete ways forward: it marks this chat Needs you. For ordinary questions, use the provider question tool. Leave a ticket handoff when linked and stop; the user can reply in this chat to continue the same session. Columns record progress; moving or creating a ticket in a column never starts an agent. Keep decisions, verification, findings, blockers, and handoffs on the ticket. Sub-work belongs to the same ticket: chats you delegate to, start, or brief from a linked chat join its ticket automatically, so never create a new ticket for part of the current one. Create tickets only when the user asks or the work is a separate deliverable. Give delegated agents the ticket key and workspace and require a handoff. A chat finishing its turn does not mean the ticket is complete. A ticket's requires lists tickets it depends on, with the column each sits in: judge from those columns whether they are finished before starting, and call request_human if they are not. A ticket can have a workspace: its own folder with a git worktree per repo on the branch ticket/<key>, shared by every chat on the ticket. get_ticket returns it. When this chat runs in that workspace, work only there, never in the repos' main checkouts, except repos listed with checkout local, which are the shared main checkout. Remove a ticket's workspace with remove_ticket_workspace only once its work is pushed or merged.
</t3_boards>

<t3_terminals>
Start long-running processes the user may want to watch (dev servers, watchers, long builds) with the t3-code MCP tool t3_terminal_start instead of backgrounding them in your own shell. Each one runs in a terminal tab of this thread named agent-<name>. Read its output with t3_terminal_read while debugging, and stop it with t3_terminal_stop. t3_terminal_read also reads the terminal tabs the user opened (term-1, term-2, ...), even after they stopped or closed: when the user mentions a terminal, server output, or an error without saying where, find it with t3_terminal_list and read it instead of starting your own copy of the process. Another thread in the same project can be read by passing its threadId. Keep using your own shell for ordinary short commands.
</t3_terminals>

<t3_chat_pins>
Each chat has pins that the user reads at a glance beside the chat and on its ticket while switching between many chats. On longer work, keep a short markdown note current with pin_note: what this chat is doing, where things run (ports, URLs), and the decisions you still need from the user; reusing a title rewrites that note. Pin documents the user will come back to, such as a smoke test guide, plan, or report, with pin_artifact (an absolute path or a URL). Remove pins that stopped mattering with unpin_artifact. Do not pin every file you touch.
</t3_chat_pins>`;
